optimize security pipeline

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,15 +1,41 @@
+#!/usr/bin/env sh
+
 echo "🔒 Running security checks..."
 
 echo "1/4 Checking secrets with Gitleaks..."
 gitleaks detect --source . --no-banner
 
+if [ $? -ne 0 ]; then
+  echo "❌ Gitleaks failed. Commit blocked."
+  exit 1
+fi
+
+
 echo "2/4 Checking secrets with TruffleHog..."
 trufflehog filesystem .
+
+if [ $? -ne 0 ]; then
+  echo "❌ TruffleHog failed. Commit blocked."
+  exit 1
+fi
+
 
 echo "3/4 Checking code security with Semgrep..."
 semgrep --config auto .
 
-echo "4/4 Checking dependencies and vulnerabilities with Trivy..."
-trivy fs .
+if [ $? -ne 0 ]; then
+  echo "❌ Semgrep failed. Commit blocked."
+  exit 1
+fi
+
+
+echo "4/4 Checking dependencies vulnerabilities with Trivy..."
+trivy fs --scanners vuln .
+
+if [ $? -ne 0 ]; then
+  echo "❌ Trivy failed. Commit blocked."
+  exit 1
+fi
+
 
 echo "✅ Security checks passed."
